version: '2'
services: 
    

    sabnzbd:
        image: ghcr.io/linuxserver/sabnzbd
        container_name: sabnzbd
        environment:
          - PUID=1000
          - PGID=1000
          - TZ=Europe/London
        volumes:
          - /data/sabnzbd/config:/config
          - /mnt/media/usenet:/downloads
          #- /path/to/downloads:/downloads #optional
          #- /path/to/incomplete/downloads:/incomplete-downloads #optional
        ports:
          - 8080:8080
          - 9090:9090
        restart: unless-stopped
    heimdall:
      image: ghcr.io/linuxserver/heimdall
      container_name: heimdall
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
      volumes:
        - /data/heimdall/config:/config
      ports:
        - 80:80
        - 443:443
      restart: unless-stopped
