
# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID
  
# Keys common to some of the core services that we always to automatically restart on failure
x-common-keys-core: &common-keys-core
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: always
 
# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys-apps
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped
 
# Keys common to some of the services in media-services.txt
x-common-keys-media: &common-keys-media
  networks:
    - npm_proxy
  security_opt:
    - no-new-privileges:true
  restart: "no"

##-{ Services }-##################################################################
services:
  npm:
  <<: *common-keys-core # See EXTENSION FIELDS at the top
  container_name: nginx-proxy-manager
  image: 'jc21/nginx-proxy-manager:latest'
  ports:
    - '80:80' # Public HTTP Port. Port Forwarding on Router is ON.
    - '443:443' # Public HTTPS Port. Port Forwarding on Router is ON.
    - '81:81' # Admin Web Port. Port Forwarding on Router is OFF. Internal Home Network Access only - 192.168.89.254:81.
  volumes:
    - $DOCKERDIR/appdata/npm/config:/config 
    - $DOCKERDIR/appdata/npm/letsencrypt:/etc/letsencrypt
    - $DOCKERDIR/appdata/npm/data:/data
  environment:
    DB_SQLITE_FILE: "/config/database.sqlite"
    DISABLE_IPV6: 'true'
