
# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:
      
  mealie-frontend:
    image: hkotel/mealie:frontend-v1.0.0beta-5
    container_name: mealie-frontend
    environment: 
      <<: *default-tz-puid-pgid
      API_URL: http://mealie-api:9000
    restart: always
    ports: 
      - 9925:3000
    volumes:
      - $DOCKERDIR/appdata/mealie/data/mealie/data/:/app/data
      
  mealie-api:
    image: hkotel/mealie:api-v1.0.0beta-5
    container_name: mealie-api
    deploy:
      resources:
        limits:
          memory: 500M
    restart: always
    ports:
      - 9926:9000
    environment: 
      <<: *default-tz-puid-pgid
      ALLOW_SIGNUP: false
      MAX_WORKERS: 1
      WEB_CONCURENCY: 1
      BASE_URL: https://${SERVER_IP}:9925
    volumes:
      - $DOCKERDIR/appdata/mealie/data/mealie/data/:/app/data   
    
    
