

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

services:

  getiplayer:
    image: ghcr.io/thespad/get_iplayer
    container_name: get_iplayer
    ports:
      - "9935:1935"
    environment:
      <<: *default-tz-puid-pgid
      INCLUDERADIO: true
      ENABLEIMPORT: true
      BASEURL: http://${SERVER_IP}:9935
    volumes:
      - $DOCKERDIR/appdata/get_iplayer:/config
      - $DATADIR/iplayer:/data

  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      <<: *default-tz-puid-pgid
      CHECK_FREQUENCY=240
      PASSWORD=${PODGRAB_PASSWORD}
    volumes:
      - ${DOCKERDIR}/appdata/podgrab:/config
      - $DATADIR/media/podcasts:/assets
    ports:
      - 1936:8080
    restart: unless-stopped
  

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
    environment:
      <<: *default-tz-puid-pgid

  radarr:
    image: lscr.io/linuxserver/radarr:nightly # latest tag was causing "Error parsing column 45"
    container_name: radarr
    ports:
      - "7878:7878"
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DATADIR:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
      
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    ports:
      - "8989:8989"
    volumes:
      - $DOCKERDIR/appdata/sonarr:/config
      - $DATADIR:/data
      - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid

  lidarr:
    image: lscr.io/linuxserver/lidarr
    container_name: ladarr
    ports:
      - "8686:8686"
    volumes:
      - $DOCKERDIR/appdata/lidarr:/config
      - $DATADIR:/data
#       - $DATADIR/media:/data/media
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      <<: *default-tz-puid-pgid
