version: "3"
services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    environment:
      DB_TYPE: sqlite
      DB_FILEPATH: /data/wiki.db
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /data/docker/wikijs/config/:/config
      - /data/docker/wikijs/database/:/data
    networks:
      - app-network
#  fretak:
#    image: freetakteam/freetakserver:1.7.5
#    container_name: WhiteWolfTak
#    environment:
#      MSG: "Welcome to White Wolf TAK"
#    restart: unless-stopped
#    ports:
#      - 5000:5000 
#      - 8080:8080 
#      - 8087:8087
#      - 8089:8089
#      - 8443:8443
#      - 19023:19023
#    volumes:
#      - /data/docker/freetak/config:/config
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /data/docker/homarr/config:/app/data/configs
      - /data/docker/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
    networks:
      - app-network
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    environment:
      X_FRAME_OPTIONS: "sameorigin"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/docker/npm:/data
    networks:
      - app-network
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
    networks:
      - app-network

  calibre:
    image: ghcr.io/linuxserver/calibre
    container_name: calibre
    environment:
      - PUID=1000 #change this to your user's PID
      - PGID=1000 #change this to your user's PGID
    volumes:
      - /data/docker/calibre/config:/config #change before the ':'
      - /data/docker/calibre/upload:/uploads #change before the ':'
      - /data/docker/calibre/plugins:/plugins #change before the ':'
      - /data/docker/calibre/library:/Calibre_Library #this is where your ebooks will end up
    ports:
      - 3002:8080 #change before the ':' if necessary
      - 3003:8081 #change before the ':' if necessary
    restart: unless-stopped
    networks:
      - app-network

  # calibre-web:
  #   image: ghcr.io/linuxserver/calibre-web
  #   container_name: calibre-web
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #   volumes:
  #     - /data/docker/calibre/web:/config
  #     - /data/docker/calibre/library:/books
  #   restart: unless-stopped
  #   ports:
  #     - 3004:8083
  #   networks:
  #     - app-network

networks:    
  app-network:
    external: true
      
      
