version: "3"
services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    environment:
      DB_TYPE: sqlite
      DB_FILEPATH: /data/wiki.db
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /data/docker/wikijs/config/:/config
      - /data/docker/wikijs/database/:/data    
#  fretak:
#    image: freetakteam/freetakserver:1.7.5
#    container_name: WhiteWolfTak
#    environment:
#      MSG: "Welcome to White Wolf TAK"
#    restart: unless-stopped
#    ports:
#      - 5000:5000 
#      - 8080:8080 
#      - 8087:8087
#      - 8089:8089
#      - 8443:8443
#      - 19023:19023
#    volumes:
#      - /data/docker/freetak/config:/config
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /data/docker/homarr/config:/app/data/configs
      - /data/docker/homarr/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '7575:7575'
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: npm
    restart: unless-stopped
    environment:
      X_FRAME_OPTIONS: "sameorigin"
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - /data/docker/npm:/data
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - '3001:3001'
    volumes:
      - /:/mnt/host:ro
      
      
